language: node_js
node_js:
- node
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - sh serverless.env.sh
script:
  - yarn lint
  - yarn test-once
  - REACT_APP_FOTOPIA_API=$FOTOPIA_API_DEV yarn build
  - npm install -g serverless
  - sls deploy -s dev
  - REACT_APP_FOTOPIA_API=$FOTOPIA_API_PROD yarn build
  - sls deploy -s prod
