language: node_js
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - sh serverless.env.sh
script:
  - yarn lint
  - yarn test-once
  - FOTOPIA_STACK_NAME=$FOTOPIA_STACK_NAME_DEV yarn getConfig
  - yarn build
  - npm install -g serverless
  - sls deploy -s dev
  - FOTOPIA_STACK_NAME=$FOTOPIA_STACK_NAME_PROD yarn getConfig
  - yarn build
  - sls deploy -s prod
